"""artifact reviews

Revision ID: fd8e2d9afd05
Revises: f9cd5a1567cf
Created: 2026-08-08 00:13:19.703522
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fd8e2d9afd05'
down_revision: str | None = 'f9cd5a1567cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('produced_by_run_id', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('deterministic_score', sa.Integer(), nullable=False),
    sa.Column('reasoning_applied', sa.Boolean(), nullable=False),
    sa.Column('reviewer_provider', sa.String(length=50), nullable=True),
    sa.Column('reviewer_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'artifact_version', name='uq_review_artifact_version')
    )
    with op.batch_alter_table('artifact_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_project', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_project')

    op.drop_table('artifact_reviews')
    # ### end Alembic commands ###
