"""agent approval request fields

Revision ID: f9cd5a1567cf
Revises: 13ecbc9568b5
Created: 2026-08-07 22:10:47.502022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f9cd5a1567cf'
down_revision: str | None = '13ecbc9568b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('approval_reason', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_column('approval_reason')
        batch_op.drop_column('requires_approval')

    # ### end Alembic commands ###
